
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: Admin007*
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: Rocket_Elevators_Information_System_development


test:
  <<: *default
  database: Rocket_Elevators_Information_System_test




production:
  <<: *default
  database: Rocket_Elevators_Information_System_production
  username: Rocket_Elevators_Information_System
  password: <%= ENV['ROCKET_ELEVATORS_INFORMATION_SYSTEM_DATABASE_PASSWORD'] %>
